Looks like I won't be able to have a unittest to detect altered sources.

diff --git a/test-suite/unit-testing/ce_tmx.pl/Makefile b/test-suite/unit-testing/ce_tmx.pl/Makefile
--- a/test-suite/unit-testing/ce_tmx.pl/Makefile
+++ b/test-suite/unit-testing/ce_tmx.pl/Makefile
@@ -118,29 +118,31 @@ xliff/%/Q.txt xliff/%/Q.tags:  %.sdlxliff
 		$(and ${FILTER}, -filter=${FILTER}) \
 		replace $* \
 		2> ${LOGS}/$(basename $(subst /,.,$@)).log
-	[[ -s $@ ]] || ! echo "ERROR replacing $@"
+	[[ -s $@ ]] || ! echo "ERROR replacing $@, empty or non existing."
 
 
 
 # Validate TMX format.
-#${TMX_LIST}:  tmx/%/val:  tmx/%/QP.xml  %.tmx
+REMOVE_DOCTYPE = <(sed -e 's/<!DOCTYPE tmx SYSTEM "tmx14.dtd">//' < $1)
 tmx/%/val:  tmx/%/QP.xml  %.tmx
-	[[ `xpath <(sed -e 's/<!DOCTYPE tmx SYSTEM "tmx14.dtd">//' < $<) 'count(//tuv[@xml:lang="FR-CA" or @xml:lang="fr-CA"])' 2> /dev/null` -eq $(call EXPECTED_FILTER, ${EXPECTED_SIZE}, $(or ${FILTER_100}, ${FILTER})) ]]
-	$(and ${SCORE}, ${FILTER}, [[ "`xpath <(sed -e 's/<!DOCTYPE tmx SYSTEM "tmx14.dtd">//' < $<) 'count(//tu/prop[@type=\"Txt::CE\"])' 2> /dev/null`" -eq $(call EXPECTED_FILTER, ${EXPECTED_SIZE}, $(or ${FILTER_100}, ${FILTER})) ]])
+	[[ `xpath $(call REMOVE_DOCTYPE, $<) 'count(//tuv[@xml:lang="FR-CA" or @xml:lang="fr-CA"])' 2> /dev/null` -eq $(call EXPECTED_FILTER, ${EXPECTED_SIZE}, $(or ${FILTER_100}, ${FILTER})) ]]
+	$(and ${SCORE}, ${FILTER}, [[ "`xpath $(call REMOVE_DOCTYPE, $<) 'count(//tu/prop[@type=\"Txt::CE\"])' 2> /dev/null`" -eq $(call EXPECTED_FILTER, ${EXPECTED_SIZE}, $(or ${FILTER_100}, ${FILTER})) ]])
 	$(if ${FILTER},, diff --ignore-matching-lines="^<file filename" <(xml_grep --nodate '//tuv[@xml:lang="EN-CA"]' $(filter %/QP.xml, $+)) <(xml_grep --nodate '//tuv[@xml:lang="EN-CA"]' $(filter %.tmx, $+)) \
-	|| ! echo "the source sentence was altered" >&2)
-	echo "validate that the source sentence is unaltered: viewdiff <(xmllint --format --recover - 2>/dev/null < $(filter %.tmx,$+))  <(xmllint --format --recover - 2>/dev/null < $(<:xml=template.xml))  <(xmllint --format --recover - 2>/dev/null < $<)"
+		|| ! echo "the source sentence was altered" >&2)
+	echo "validate that the source sentence is unaltered: viewdiff <(xmllint --format --recover - 2>/dev/null < $(filter %.tmx,$+))  <(xmllint --format --recover - 2>/dev/null < $(<:xml=template.xml))  <(xmllint --format --recover - 2>/dev/null < $<) +/xml:lang=\\\"EN-CA\\\""
 
 # Validate sdlxliff format.
-#$(filter-out xliff/unittest1/val, ${XLIFF_LIST}):  xliff/%/val:  xliff/%/QP.xml
+GET_SOURCES = perl -nle 'BEGIN{$$/=undef}; s/<mrk[^>]+>//g; while (m/(<source.*?\/source>|<seg-source.*?\/seg-source>)/g) {print "line $$1\n"}' $1
+STRIP_1E_1f = <(sed 's/&\#x1[eEfF];//g;' $1)
 xliff/%/val:  xliff/%/QP.xml  %.sdlxliff
-	[[ "`xpath $< 'count(//target[not(@*)]//mrk[@mtype=\"seg\"])' 2> /dev/null`" -eq "$(call EXPECTED_FILTER, ${EXPECTED_SIZE}, ${FILTER_100})" ]] \
-	|| ! echo "ERROR: There are some target with attributs" >&2
-	[[ "`xpath $< 'count(//target//mrk)' 2> /dev/null`" -eq "$(call EXPECTED_FILTER, ${EXPECTED_SIZE}, ${FILTER_100})" ]] \
-	|| ! echo "ERROR: There is not the right number of mrk segments." >&2 
-	$(and ${SCORE}, ${FILTER}, [[ "`xpath $< 'count(//sdl:seg-defs/sdl:seg[@percent >=0 and @percent<=100])' 2> /dev/null`" -le "$(call EXPECTED_FILTER, ${EXPECTED_SIZE}, ${FILTER_100})" ]] || ! echo "ERROR: Filtering" >&2)
-	$(if ${FILTER},, diff --ignore-matching-lines="^<file filename" <(xml_grep --nodate '//source' $(filter %/QP.xml, $+)) <(xml_grep --nodate '//source' $(filter %.sdlxliff, $+)) \
-	|| ! echo "the source sentence was altered" >&2)
+	[[ "`xpath $(call STRIP_1E_1f, $<) 'count(//target[not(@*)]//mrk[@mtype=\"seg\"])' 2> /dev/null`" -eq "$(call EXPECTED_FILTER, ${EXPECTED_SIZE}, ${FILTER_100})" ]] \
+		|| ! echo "ERROR: There are some target with attributs" >&2
+	[[ "`xpath $(call STRIP_1E_1f, $<) 'count(//target//mrk)' 2> /dev/null`" -eq "$(call EXPECTED_FILTER, ${EXPECTED_SIZE}, ${FILTER_100})" ]] \
+		|| ! echo "ERROR: There is not the right number of mrk segments." >&2 
+	$(and ${SCORE}, ${FILTER}, [[ "`xpath $(call STRIP_1E_1f, $<) 'count(//sdl:seg-defs/sdl:seg[@percent >=0 and @percent<=100])' 2> /dev/null`" -le "$(call EXPECTED_FILTER, ${EXPECTED_SIZE}, ${FILTER_100})" ]] \
+		|| ! echo "ERROR: Filtering" >&2)
+	$(if ${FILTER},, diff --ignore-all-space <($(call GET_SOURCES, $(filter %/QP.xml, $+))) <($(call GET_SOURCES, $(filter %.sdlxliff, $+))); \
+		echo "Visually make sure the sources are identical except for > &gt;" >&2)
 
 
 
