Convert all the plugins to bash 3 syntax.
 - Use [[ ]] instead of test or [ ]
 - Use = instead of ==
 - Use || instead of -o
 - Remove superfluous quotes.

E.g.: Use
   if [[ $var = value1 || $var = value2 ]]; then
instead of
   if [ "$var" == "value1" -o "$var" == "value2" ]; then

diff --git a/src/textutils/detokenize_plugin b/src/textutils/detokenize_plugin
--- a/src/textutils/detokenize_plugin
+++ b/src/textutils/detokenize_plugin
@@ -1,5 +1,4 @@
 #!/bin/bash
-# $Id$
 
 # @file tokenize_plugin
 # @brief This script is provided as an example of detokenize_plugin script.
@@ -20,15 +19,15 @@
 ## postprocess_plugin but after truecasing.
 ##
 
-if [ "$1" == "-help" -o "$1" == "-h" ]; then
+if [[ $1 = -help || $1 = -h ]]; then
     cat $0 | grep "^##" | cut -c4-
     exit 1
 fi
 
-test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
+[[ $# = 0 ]] && echo "Missing language code argument" >&2 && exit 1
 TARGET_LANGUAGE=$1; shift
 
-if [ "$TARGET_LANGUAGE" == "fr" -o "$TARGET_LANGUAGE" == "en" -o "$TARGET_LANGUAGE" == "es" ]; then
+if [[ $TARGET_LANGUAGE = fr || $TARGET_LANGUAGE = en || $TARGET_LANGUAGE = es ]]; then
    udetokenize.pl -lang=$TARGET_LANGUAGE
 else
    echo "Unsupported language: $TARGET_LANGUAGE" >&2
diff --git a/src/textutils/postdecode_plugin b/src/textutils/postdecode_plugin
--- a/src/textutils/postdecode_plugin
+++ b/src/textutils/postdecode_plugin
@@ -25,12 +25,12 @@
 #          Also, the input to the postdecode_plugin may contain XML markup
 #          identifying OOVs.
 
-if [ "$1" == "-help" -o "$1" == "-h" ]; then
+if [[ $1 = -help || $1 = -h ]]; then
     cat $0 | grep "^##" | cut -c4-
     exit 1
 fi
 
-test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
+[[ $# = 0 ]] && echo "Missing language code argument" >&2 && exit 1
 TARGET_LANGUAGE=$1; shift
 
 exec cat
diff --git a/src/textutils/postprocess_plugin b/src/textutils/postprocess_plugin
--- a/src/textutils/postprocess_plugin
+++ b/src/textutils/postprocess_plugin
@@ -19,12 +19,12 @@
 ## Default postprocessing plugin: to be called after detokenization.
 ##
 
-if [ "$1" == "-help" -o "$1" == "-h" ]; then
+if [[ $1 = -help || $1 = -h ]]; then
     cat $0 | grep "^##" | cut -c4-
     exit 1
 fi
 
-test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
+[[ $# = 0 ]] && echo "Missing language code argument" >&2 && exit 1
 TARGET_LANGUAGE=$1; shift
 
 # Suggestion: for an English->French system, you could use fix-en-fr-numbers.pl
diff --git a/src/textutils/predecode_plugin b/src/textutils/predecode_plugin
--- a/src/textutils/predecode_plugin
+++ b/src/textutils/predecode_plugin
@@ -21,12 +21,12 @@
 ## Among other things, the predecoding plugin must apply the rules parser.
 ##
 
-if [ "$1" == "-help" -o "$1" == "-h" ]; then
+if [[ $1 = -help || $1 = -h ]]; then
     cat $0 | grep "^##" | cut -c4-
     exit 1
 fi
 
-test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
+[[ $# = 0 ]] && echo "Missing language code argument" >&2 && exit 1
 SOURCE_LANGUAGE=$1; shift
 
 # If you have a rules parser, replace the canoe-escapes.pl call by a call to your
diff --git a/src/textutils/preprocess_plugin b/src/textutils/preprocess_plugin
--- a/src/textutils/preprocess_plugin
+++ b/src/textutils/preprocess_plugin
@@ -19,12 +19,12 @@
 ## Default preprocessing plugin, to be called prior to tokenization
 ##
 
-if [ "$1" == "-help" -o "$1" == "-h" ]; then
+if [[ $1 = -help || $1 = -h ]]; then
     cat $0 | grep "^##" | cut -c4-
     exit 1
 fi
 
-test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
+[[ $# = 0 ]] && echo "Missing language code argument" >&2 && exit 1
 SOURCE_LANGUAGE=$1; shift
 
 # The following does minimalist preprocessing: remove the UTF8 bit-order mark,
diff --git a/src/textutils/sentsplit_plugin b/src/textutils/sentsplit_plugin
--- a/src/textutils/sentsplit_plugin
+++ b/src/textutils/sentsplit_plugin
@@ -29,18 +29,18 @@
 ## supported by utokenize.pl.
 ##
 
-if [ "$1" == "-help" -o "$1" == "-h" ]; then
+if [[ $1 == -help || $1 == -h ]]; then
     cat $0 | grep "^##" | cut -c4-
     exit 1
 fi
 
-test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
+[[ $# = 0 ]] && echo "Missing language code argument" >&2 && exit 1
 SOURCE_LANGUAGE=$1; shift
 
-if [[ "$SOURCE_LANGUAGE" == "ch" ]]; then
+if [[ $SOURCE_LANGUAGE = ch || $SOURCE_LANGUAGE = zh ]]; then
    perl -ple 'BEGIN{use encoding "UTF-8";} s/(\.\.\.\.\.\.|\.\.\.|\x{2026}{1,2}|\.(?![0-9])|\x{FF0E}|\x3F|\x{FF1F}|\x21|\x{FF01}|\x{3002}|\x{FF61})/$1\n/g; s/\n*$/\n/;'
 
-#elif [[ "SOURCE_LANGUAGE" == "xy" ]]; then
+#elif [[ $SOURCE_LANGUAGE = xy ]]; then
    # insert code or call program to do sentence splitting for language "xy"
    # here, reading STDIN and writing to STDOUT.
 
diff --git a/src/textutils/tokenize_plugin b/src/textutils/tokenize_plugin
--- a/src/textutils/tokenize_plugin
+++ b/src/textutils/tokenize_plugin
@@ -25,15 +25,15 @@
 ## utokenize.pl.
 ##
 
-if [ "$1" == "-help" -o "$1" == "-h" ]; then
+if [[ $1 = -help || $1 = -h ]]; then
     cat $0 | grep "^##" | cut -c4-
     exit 1
 fi
 
-test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
+[[ $# = 0 ]] && echo "Missing language code argument" >&2 && exit 1
 SOURCE_LANGUAGE=$1; shift
 
-if [[ "$SOURCE_LANGUAGE" == "ch" ]]; then
+if [[ $SOURCE_LANGUAGE = ch || $SOURCE_LANGUAGE = zh ]]; then
    chinese_segmenter.pl
    # To use ICTCLAS, comment out chinese_segmenter.pl above, and uncomment the following:
    #set -o pipefail
@@ -43,11 +43,11 @@ if [[ "$SOURCE_LANGUAGE" == "ch" ]]; then
    #   ictclas_postprocessing.pl |
    #   iconv -c -f CN-GB -t UTF-8
 
-#elif [[ "$SOURCE_LANGUAGE" == "xy" ]]; then
+#elif [[ $SOURCE_LANGUAGE = xy ]]; then
    # insert code or call program to tokenize text in language "xy" here,
    # reading STDIN and writing to STDOUT.
 
-elif [[ "$SOURCE_LANGUAGE" == "ar" ]]; then
+elif [[ $SOURCE_LANGUAGE = ar ]]; then
    export PATH=`dirname $0`:$PATH
 
    TMPFILE=`mktemp -d /tmp/ar_tokenization.XXXXXXXXXX` || exit 1
