Added (de)tokenize_plugin to support Chinese.

diff --git a/src/textutils/postdecode_plugin b/src/textutils/postdecode_plugin
--- a/src/textutils/postdecode_plugin
+++ b/src/textutils/postdecode_plugin
@@ -17,7 +17,7 @@
 #############################################################
 
 ## 
-## Usage: postdecode_plugin < in > out
+## Usage: postdecode_plugin TGT_LANG < in > out
 ## 
 ## Default postdecoding plugin: to be called immediately after decoding.
 ##
@@ -32,5 +32,8 @@ if [ "$1" == "-help" -o "$1" == "-h" ]; then
     cat $0 | grep "^##" | cut -c4-
     exit 1
 fi
+
+test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
+LANG=$1; shift
 
 exec cat
diff --git a/src/textutils/postprocess_plugin b/src/textutils/postprocess_plugin
--- a/src/textutils/postprocess_plugin
+++ b/src/textutils/postprocess_plugin
@@ -17,7 +17,7 @@
 #############################################################
 
 ## 
-## Usage: postprocess_plugin < in > out
+## Usage: postprocess_plugin TGT_LANG < in > out
 ## 
 ## Default postprocessing plugin: to be called after detokenization.
 ##
@@ -26,6 +26,9 @@ if [ "$1" == "-help" -o "$1" == "-h" ]; then
     cat $0 | grep "^##" | cut -c4-
     exit 1
 fi
+
+test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
+LANG=$1; shift
 
 exec cat
 
diff --git a/src/textutils/predecode_plugin b/src/textutils/predecode_plugin
--- a/src/textutils/predecode_plugin
+++ b/src/textutils/predecode_plugin
@@ -17,7 +17,7 @@
 #############################################################
 
 ## 
-## Usage: predecode_plugin < in > out
+## Usage: predecode_plugin SRC_LANG < in > out
 ## 
 ## Default predecoding plugin: to be called immediately prior to
 ## decoding (but after tokenization, lowercasing, etc.).
@@ -28,6 +28,9 @@ if [ "$1" == "-help" -o "$1" == "-h" ]; then
     cat $0 | grep "^##" | cut -c4-
     exit 1
 fi
+
+test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
+LANG=$1; shift
 
 # If you have a rules parser, replace the canoe-escapes.pl call by a call to your
 # rules parser. The rules parser must also escape literal use of the following 
diff --git a/src/textutils/preprocess_plugin b/src/textutils/preprocess_plugin
--- a/src/textutils/preprocess_plugin
+++ b/src/textutils/preprocess_plugin
@@ -17,7 +17,7 @@
 #############################################################
 
 ## 
-## Usage: preprocess_plugin < in > out
+## Usage: preprocess_plugin SRC_LANG < in > out
 ## 
 ## Default preprocessing plugin, to be called prior to tokenization
 ##
@@ -26,6 +26,9 @@ if [ "$1" == "-help" -o "$1" == "-h" ]; then
     cat $0 | grep "^##" | cut -c4-
     exit 1
 fi
+
+test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
+LANG=$1; shift
 
 ridbom.sh | crlf2lf.sh
 
