Fix Chinese sentence splitter to not split on decimal number.
Also remove unecessary test and specialized error message in sentsplit_plugin
and tokenize_plugin for languages supported by utokenized.pl.

diff --git a/src/textutils/sentsplit_plugin b/src/textutils/sentsplit_plugin
--- a/src/textutils/sentsplit_plugin
+++ b/src/textutils/sentsplit_plugin
@@ -1,5 +1,4 @@
 #!/bin/bash
-# $Id$
 
 # @file sentsplit_plugin
 # @brief This script is provided as an example of sentsplit_plugin script, as
@@ -39,18 +38,14 @@ test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
 SOURCE_LANGUAGE=$1; shift
 
 if [[ "$SOURCE_LANGUAGE" == "ch" ]]; then
-   perl -ple 'BEGIN{use encoding "UTF-8";} s/(\.\.\.\.\.\.|\.\.\.|\x{2026}{1,2}|\x2E|\x{FF0E}|\x3F|\x{FF1F}|\x21|\x{FF01}|\x{3002}|\x{FF61})/$1\n/g; s/\n*$/\n/;'
+   perl -ple 'BEGIN{use encoding "UTF-8";} s/(\.\.\.\.\.\.|\.\.\.|\x{2026}{1,2}|\.(?![0-9])|\x{FF0E}|\x3F|\x{FF1F}|\x21|\x{FF01}|\x{3002}|\x{FF61})/$1\n/g; s/\n*$/\n/;'
 
 #elif [[ "SOURCE_LANGUAGE" == "xy" ]]; then
    # insert code or call program to do sentence splitting for language "xy"
    # here, reading STDIN and writing to STDOUT.
 
-elif [ "$SOURCE_LANGUAGE" == "fr" -o "$SOURCE_LANGUAGE" == "en" -o "$SOURCE_LANGUAGE" == "es" -o "$SOURCE_LANGUAGE" == "da" ]; then
-   echo "Language $SOURCE_LANGUAGE is supported by utokenize.pl, don't use the plugin" >&2
-   exit 1
-
 else
-   echo "Unsupported language: $SOURCE_LANGUAGE" >&2
+   echo "sentsplit_plugin fatal error: Unsupported language: $SOURCE_LANGUAGE; use utokenize.pl -ss for languages it supports, or modify this plugin to call a third-party sentence splitter." >&2
    exit 1
 
 fi
diff --git a/src/textutils/tokenize_plugin b/src/textutils/tokenize_plugin
--- a/src/textutils/tokenize_plugin
+++ b/src/textutils/tokenize_plugin
@@ -103,12 +103,9 @@ elif [[ "$SOURCE_LANGUAGE" == "ar" ]]; then
    fi
 
 
-elif [ "$SOURCE_LANGUAGE" == "fr" -o "$SOURCE_LANGUAGE" == "en" -o "$SOURCE_LANGUAGE" == "es" ]; then
-   echo "Language $SOURCE_LANGUAGE is supported by utokenize.pl, don't use the plugin" >&2
-   exit 1
-
 else
    echo "Unsupported language: $SOURCE_LANGUAGE" >&2
+   echo "tokenize_plugin fatal error: Unsupported language: $SOURCE_LANGUAGE; use utokenize.pl for languages it supports, or modify this plugin to call a third-party tokenizer." >&2
    exit 1
 
 fi
